<?php

namespace House\Bundle\Repository;

/**
 * AdDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
