<?php

namespace House\Bundle\Repository;

/**
 * ImagesSmallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagesSmallRepository extends \Doctrine\ORM\EntityRepository
{
}
