<?php

namespace House\Bundle\Repository;

/**
 * RentalDatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentalDatesRepository extends \Doctrine\ORM\EntityRepository
{
}
