<?php

namespace House\Bundle\Repository;

/**
 * SalesRentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesRentRepository extends \Doctrine\ORM\EntityRepository
{
}
