imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: en

framework:
    translator:
        paths:
            - '%kernel.root_dir%/../src/House/Bundle/Resources/translations'
#     { fallbacks : [%locale%] }
    default_locale: en
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        handler_id: ~
    fragments: ~
    http_method_override: true

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    HouseBundle:  ~
                    ApplicationSonataUserBundle: ~
                    SonataUserBundle: ~
                    FOSUserBundle: ~
sonata_block:
  default_contexts: [cms]
  blocks:
    # Enable the SonataAdminBundle block
    sonata.admin.block.admin_list:
      contexts:  [admin]
    sonata.user.block.menu:  # used to display the menu in profile pages
    sonata.user.block.account: # used to display menu option (login option)
    sonata.block.service.text: # used to if you plan to use Sonata user routes

sonata_user:
  manager_type: orm

fos_user:
  db_driver:  orm
  firewall_name:  main
  user_class:  Application\Sonata\UserBundle\Entity\User
  from_email:
    address: '%mailer_user%'
    sender_name: Anthony
  group:
    group_class:  Application\Sonata\UserBundle\Entity\Group
    group_manager: sonata.user.orm.group_manager
  service:
    user_manager: sonata.user.orm.user_manager

sonata_user:
    manager_type: orm

sonata_admin:
    show_mosaic_button: false

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

genemu_form:
    tinymce: ~

white_october_breadcrumbs: ~

vich_uploader:
    db_driver: orm
    mappings:
        house:
            uri_prefix:         /web/upload/house
            upload_destination: %kernel.root_dir%/../web/upload/house
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        housesmall:
            uri_prefix:         /web/upload/house
            upload_destination: %kernel.root_dir%/../web/upload/house
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true