homepage:
    path:     /{_locale}
    defaults: { _controller: HouseBundle:Default:index }
    requirements:
        _locale: en|ru|ar
homepage_nolang:
    path:     /
    defaults: { _controller: HouseBundle:Default:index }

contactus:
    path:  /contactus
    defaults: { _controller: "HouseBundle:ContactUS:index" }
    requirements:
        methods:  GET|POST
contact:
    path:  /contact
    defaults: { _controller: "HouseBundle:Default:contact" }
    requirements:
        methods:  GET|POST
salesrenthome:
    path:  /salesrenthome
    defaults: { _controller: "HouseBundle:Default:ajax" }
    requirements:
        methods:  GET|POST
loadmoreprod:
    path:  /loadmoreprod
    defaults: { _controller: "HouseBundle:Default:loadMoreAjax" }
    requirements:
        methods:  GET|POST
loadmoreparam:
    path:  /loadmoreparam
    defaults: { _controller: "HouseBundle:Parameters:loadMoreAjax" }
    requirements:
        methods:  GET|POST
get:
    resource: "@HouseBundle/Controller/ParametersController.php"
    type:     annotation
    requirements:
        methods:  GET|POST
product:
    path:  /{_locale}/product/{name}
    defaults: { _controller: HouseBundle:Product:index }
    requirements:
        _locale: en|ru|ar