homepage:
    path:     /
    defaults: { _controller: HouseBundle:Default:index }
contactus:
    path:  /contactus
    defaults: { _controller: "HouseBundle:ContactUS:index" }
    requirements:
        methods:  GET|POST
contact:
    path:  /contact
    defaults: { _controller: "HouseBundle:Default:contact" }
    requirements:
        methods:  GET|POST